name: awbd
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: jp_user
      POSTGRES_PASSWORD: jp_pass
      POSTGRES_DB: jp_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  pg_data:
